#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generate the Security Triage agent's config.yaml from NemoClaw's injected env
# vars. Invoked inside the sandbox by NemoClaw's onboarding config step.
# Deliberately minimal: writes only non-secret model/base-url metadata for
# operator inspection. ANTHROPIC_API_KEY is NOT written here -- it stays in the
# process environment, read directly by the anthropic SDK.

import os
from pathlib import Path

CONFIG_DIR = Path("/sandbox/.security-triage")


def main() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    model = os.environ.get("NEMOCLAW_MODEL", "").strip()
    base_url = os.environ.get("NEMOCLAW_INFERENCE_BASE_URL", "").strip()
    config = (
        "# Generated by generate_config.py — do not edit by hand.\n"
        "model:\n"
        f"  default: {model!r}\n"
        f"  base_url: {base_url!r}\n"
    )
    config_path = CONFIG_DIR / "config.yaml"
    config_path.write_text(config)
    os.chmod(config_path, 0o644)


if __name__ == "__main__":
    main()
